# Generated by Django 3.1.7 on 2021-03-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterfictionassociation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiction_char', to='character_finder_api.character'),
        ),
        migrations.AlterField(
            model_name='characterfictionassociation',
            name='fiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_fiction', to='character_finder_api.fiction'),
        ),
    ]
