# Generated by Django 3.1.7 on 2021-03-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0002_auto_20210309_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='died_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorfictionassociation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiction_author', to='character_finder_api.author'),
        ),
        migrations.AlterField(
            model_name='authorfictionassociation',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_fiction', to='character_finder_api.fiction'),
        ),
        migrations.AlterField(
            model_name='characterfictionassociation',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiction_char', to='character_finder_api.character'),
        ),
        migrations.AlterField(
            model_name='characterfictionassociation',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_fiction', to='character_finder_api.fiction'),
        ),
        migrations.AlterField(
            model_name='characterfictionassociation',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char_series', to='character_finder_api.series'),
        ),
    ]
