# Generated by Django 3.1.7 on 2021-03-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0003_auto_20210311_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorfictionassociation',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiction_series', to='character_finder_api.series'),
        ),
        migrations.AlterField(
            model_name='characterassociation',
            name='char_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charone', to='character_finder_api.character'),
        ),
        migrations.AlterField(
            model_name='characterassociation',
            name='char_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartwo', to='character_finder_api.character'),
        ),
    ]
