# Generated by Django 3.1.7 on 2021-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0003_charactereditqueue_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactereditqueue',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
