# Generated by Django 3.1.7 on 2021-03-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0004_auto_20210312_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorfictionassociation',
            name='series',
        ),
    ]
