# Generated by Django 3.1.7 on 2021-03-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_finder_api', '0004_auto_20210318_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
